name: 'wakatime-gcal-exporter'
description: 'Sync wakatime stats to google calender'
author: 'hijiki51'
inputs:
  access_token:
    description: 'Access token for Google Cloud'
    required: true
  wakatime-api-key:
    required: true
    description: 'wakatime api key'
  calendar-id:
    required: true
    description: 'google calendar id'
  color-id:
    description: 'google calendar color id'
  projects: 
    description: 'filter project names. if empty, all projects are exported'
runs:
  using: 'node16'
  main: 'dist/index.js'
