name: 'wakatime-gcal-exporter'
description: 'Sync wakatime stats to google calender'
author: 'hijiki51'
inputs:
  wakatime_api_key: # change this
    required: true
    description: 'wakatime api key'
runs:
  using: 'node16'
  main: 'dist/index.js'
